export const ERROR_CODES = {
  VALIDATION_FAILED: 'FINTRACK_ERR_4000',
  UNAUTHENTICATED: 'FINTRACK_ERR_4010',
  FORBIDDEN: 'FINTRACK_ERR_4030',
  NOT_FOUND: 'FINTRACK_ERR_4040',
  METHOD_NOT_ALLOWED: 'FINTRACK_ERR_4050',
  CONFLICT: 'FINTRACK_ERR_4090',
  IDEMPOTENCY_REQUIRED: 'FINTRACK_ERR_4091',
  UNSUPPORTED_MEDIA_TYPE: 'FINTRACK_ERR_4150',
  RATE_LIMITED: 'FINTRACK_ERR_4290',
  INTERNAL: 'FINTRACK_ERR_5000',
  DEPENDENCY_UNAVAILABLE: 'FINTRACK_ERR_5030',
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
