export const ERROR_CODES = {
  // 4xxx — Client errors
  VALIDATION_FAILED: 'FINTRACK_ERR_4000',
  UNAUTHENTICATED: 'FINTRACK_ERR_4010',
  TOKEN_EXPIRED: 'FINTRACK_ERR_4011',
  TOKEN_REVOKED: 'FINTRACK_ERR_4012',
  SUBSCRIPTION_REQUIRED: 'FINTRACK_ERR_4020',
  FORBIDDEN: 'FINTRACK_ERR_4030',
  NOT_FOUND: 'FINTRACK_ERR_4040',
  METHOD_NOT_ALLOWED: 'FINTRACK_ERR_4050',
  CONFLICT: 'FINTRACK_ERR_4090',
  IDEMPOTENCY_REQUIRED: 'FINTRACK_ERR_4091',
  DUPLICATE_EMAIL: 'FINTRACK_ERR_4092',
  INVALID_CREDENTIALS: 'FINTRACK_ERR_4093',
  DELETION_PENDING: 'FINTRACK_ERR_4094',
  UNSUPPORTED_MEDIA_TYPE: 'FINTRACK_ERR_4150',
  RATE_LIMITED: 'FINTRACK_ERR_4290',

  // 5xxx — Server errors
  INTERNAL: 'FINTRACK_ERR_5000',
  DATABASE_ERROR: 'FINTRACK_ERR_5010',
  DEPENDENCY_UNAVAILABLE: 'FINTRACK_ERR_5030',
  AI_PROVIDER_ERROR: 'FINTRACK_ERR_5040',
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
