export const piiRedactionPaths = [
  'req.headers.authorization',
  'req.headers.cookie',
  'request.headers.authorization',
  'request.headers.cookie',
  'headers.authorization',
  'headers.cookie',
  'password',
  'passwordHash',
  'token',
  'accessToken',
  'refreshToken',
  'gmailToken',
  'gmailTokenEnc',
  'accountNumber',
  'account.accountNumber',
  'email.raw',
  'email.body',
  'rawSnippet',
  'rawSnippetEnc',
  'payload.data.authorization',
  'payload.authorization',
] as const
